export type BibleBook = { name: string; abbrev: string; chapters: number };

export const OLD_TESTAMENT: BibleBook[] = [
  { name: "Gênesis", abbrev: "genesis", chapters: 50 },
  { name: "Êxodo", abbrev: "exodus", chapters: 40 },
  { name: "Levítico", abbrev: "leviticus", chapters: 27 },
  { name: "Números", abbrev: "numbers", chapters: 36 },
  { name: "Deuteronômio", abbrev: "deuteronomy", chapters: 34 },
  { name: "Josué", abbrev: "joshua", chapters: 24 },
  { name: "Juízes", abbrev: "judges", chapters: 21 },
  { name: "Rute", abbrev: "ruth", chapters: 4 },
  { name: "1 Samuel", abbrev: "1 samuel", chapters: 31 },
  { name: "2 Samuel", abbrev: "2 samuel", chapters: 24 },
  { name: "1 Reis", abbrev: "1 kings", chapters: 22 },
  { name: "2 Reis", abbrev: "2 kings", chapters: 25 },
  { name: "1 Crônicas", abbrev: "1 chronicles", chapters: 29 },
  { name: "2 Crônicas", abbrev: "2 chronicles", chapters: 36 },
  { name: "Esdras", abbrev: "ezra", chapters: 10 },
  { name: "Neemias", abbrev: "nehemiah", chapters: 13 },
  { name: "Ester", abbrev: "esther", chapters: 10 },
  { name: "Jó", abbrev: "job", chapters: 42 },
  { name: "Salmos", abbrev: "psalms", chapters: 150 },
  { name: "Provérbios", abbrev: "proverbs", chapters: 31 },
  { name: "Eclesiastes", abbrev: "ecclesiastes", chapters: 12 },
  { name: "Cânticos", abbrev: "song of solomon", chapters: 8 },
  { name: "Isaías", abbrev: "isaiah", chapters: 66 },
  { name: "Jeremias", abbrev: "jeremiah", chapters: 52 },
  { name: "Lamentações", abbrev: "lamentations", chapters: 5 },
  { name: "Ezequiel", abbrev: "ezekiel", chapters: 48 },
  { name: "Daniel", abbrev: "daniel", chapters: 12 },
  { name: "Oseias", abbrev: "hosea", chapters: 14 },
  { name: "Joel", abbrev: "joel", chapters: 3 },
  { name: "Amós", abbrev: "amos", chapters: 9 },
  { name: "Obadias", abbrev: "obadiah", chapters: 1 },
  { name: "Jonas", abbrev: "jonah", chapters: 4 },
  { name: "Miqueias", abbrev: "micah", chapters: 7 },
  { name: "Naum", abbrev: "nahum", chapters: 3 },
  { name: "Habacuque", abbrev: "habakkuk", chapters: 3 },
  { name: "Sofonias", abbrev: "zephaniah", chapters: 3 },
  { name: "Ageu", abbrev: "haggai", chapters: 2 },
  { name: "Zacarias", abbrev: "zechariah", chapters: 14 },
  { name: "Malaquias", abbrev: "malachi", chapters: 4 },
];

export const NEW_TESTAMENT: BibleBook[] = [
  { name: "Mateus", abbrev: "matthew", chapters: 28 },
  { name: "Marcos", abbrev: "mark", chapters: 16 },
  { name: "Lucas", abbrev: "luke", chapters: 24 },
  { name: "João", abbrev: "john", chapters: 21 },
  { name: "Atos", abbrev: "acts", chapters: 28 },
  { name: "Romanos", abbrev: "romans", chapters: 16 },
  { name: "1 Coríntios", abbrev: "1 corinthians", chapters: 16 },
  { name: "2 Coríntios", abbrev: "2 corinthians", chapters: 13 },
  { name: "Gálatas", abbrev: "galatians", chapters: 6 },
  { name: "Efésios", abbrev: "ephesians", chapters: 6 },
  { name: "Filipenses", abbrev: "philippians", chapters: 4 },
  { name: "Colossenses", abbrev: "colossians", chapters: 4 },
  { name: "1 Tessalonicenses", abbrev: "1 thessalonians", chapters: 5 },
  { name: "2 Tessalonicenses", abbrev: "2 thessalonians", chapters: 3 },
  { name: "1 Timóteo", abbrev: "1 timothy", chapters: 6 },
  { name: "2 Timóteo", abbrev: "2 timothy", chapters: 4 },
  { name: "Tito", abbrev: "titus", chapters: 3 },
  { name: "Filemom", abbrev: "philemon", chapters: 1 },
  { name: "Hebreus", abbrev: "hebrews", chapters: 13 },
  { name: "Tiago", abbrev: "james", chapters: 5 },
  { name: "1 Pedro", abbrev: "1 peter", chapters: 5 },
  { name: "2 Pedro", abbrev: "2 peter", chapters: 3 },
  { name: "1 João", abbrev: "1 john", chapters: 5 },
  { name: "2 João", abbrev: "2 john", chapters: 1 },
  { name: "3 João", abbrev: "3 john", chapters: 1 },
  { name: "Judas", abbrev: "jude", chapters: 1 },
  { name: "Apocalipse", abbrev: "revelation", chapters: 22 },
];

export const ALL_BOOKS = [...OLD_TESTAMENT, ...NEW_TESTAMENT];

export function findBook(abbrev: string) {
  return ALL_BOOKS.find((b) => b.abbrev === abbrev);
}
